apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-uwb-deployment
  labels:
    app: uwb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uwb
  template:
    metadata:
      labels:
        app: uwb
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "checking"; while ! nc -z af-az-mysql-service 3306; do echo "$(date): not yet connected..." ; sleep 1; done; echo -e "we are ready"']
        - name: init-create-webappdb
          image: mysql:5.7.22
          command:
            - mysql
          args:
            - "-haf-az-mysql-service"
            - "-uhost1812@af-db0.mysql.database.azure.com"
            - "-ptesttest1!"
            - -e CREATE DATABASE [IF NOT EXISTS] webappdb;
      containers:
        - name: uwb
          image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: app
          env:
            - name: DB_HOSTNAME
              value: "af-az-mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "webappdb"
            - name: DB_USERNAME
              value: "host1812@af-db0.mysql.database.azure.com"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: af-mysql-password
                  key: db-password
