controller:
  replicaCount: 4
  controller.nodeSelector."kubernetes\.io/os": linux
  defaultBackend.nodeSelector."kubernetes\.io/os": linux
  controller.service.externalTrafficPolicy: Local
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "sleep 5; /usr/local/openresty/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done"]
  terminationGracePeriodSeconds: 600
