apiVersion: v1
kind: ConfigMap
metadata:
  name: aftest-configmap-frontend
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            proxy_pass http://aftest-backend-service:8080;
        }
      }
    }
