apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: af-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: af-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent
              mountPath: /var/lib/mysql
            - name: mysql-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent
          persistentVolumeClaim:
            claimName: af-azure-managed-disk-pvc
        - name: mysql-script
          configMap:
            name: af-usermanagement-configmap
