apiVersion: apps/v1
kind: Deployment
metadata:
  name: aftest-deployment-frontend
  labels:
    app: aftest-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aftest-frontend
  template:
    metadata:
      labels:
        app: aftest-frontend
        tier: frontend
    spec:
      containers:
        - name: aftest-frontend-nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: aftest-configmap-frontend
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: aftest-configmap-frontend
        configMap:
          name: aftest-configmap-frontend
          items:
            - key: nginx.conf
              path: nginx.conf
