apiVersion: apps/v1
kind: Deployment
metadata:
  name: aftest-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: aftestapp
  template:
    metadata:
      name: aftestapp-pod
      labels:
        app: aftestapp
    spec:
      containers:
        - name: aftestapp-container
          image: stacksimplify/kubenginx:3.0.0
          ports:
            - containerPort: 80
