apiVersion: v1
kind: Service
metadata:
  name: aftest-frontend-service
  labels:
    app: aftest-frontend
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: aftest-frontend
  ports:
    - port: 80
      targetPort: 80
